services:

  # caddy:
  #   image: caddy:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - ./site:/srv/files
  #   restart: unless-stopped

  cron-jobs:
    build: 
      context: .
      dockerfile: ./cron_jobs/Dockerfile
    container_name: cron-jobs
    volumes:
      - ./cron_jobs/eero.cookie:/eero.cookie
      - ./dnsmasq/hosts:/etc/hosts
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DESEC_TOKEN
    restart: unless-stopped

  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq/hosts:/etc/hosts
    ports:
      - "53:53/udp"  # DNS port
      - "5380:8080"  # Web UI
    restart: unless-stopped
    # networks:
    #   default:
    #     ipv4_address: 172.18.0.2  # Optional static IP for easy reference

# networks:
#   default:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.18.0.0/16
